### ISSUE TITLE
xmlschemavalidationexception

### ISSUE THREAD

**Issue by ronen009** [Giorgi/LINQPad.QueryPlanVisualizer#16] opened 2016-09-28 12:13 UTC
Hello,
First of all, I would like to thank you for this great tool. 
I have been trying to use but encountered this exception.

I do get results so the query is fine. 
I get this exception for any query  wrote. So i am posting just a simple one.

I searched about this exception but no success.
thanks!

![linqpadexception](https://cloud.githubusercontent.com/assets/14289543/18913011/20c0b68a-858e-11e6-87cb-179400dc123b.GIF)

**Comment by Giorgi** [comment] 2016-09-28 18:28
This is duplicate of #14 It is fixed in the source but I haven't published a release yet.

**Closed by Giorgi** 2016-09-28 18:28 UTC
